# Game window settings
WIDTH = 600
HEIGHT = 800
FPS = 60

# Physics settings
GRAVITY = 0.1
BOUNCE_DAMPENING = 0.98
MIN_VELOCITY = 4
ZOOM_SPEED = 0.25

# Ball settings
BALL_RADIUS = 30
BALL_TRAIL_LENGTH = 25
BALL_TEXT_SIZE = 20

# Score display
SCORE_POSITION_1 = (WIDTH//2 - 80, 30)
SCORE_POSITION_2 = (WIDTH//2 + 20, 30)

# Circle settings
FIRST_INNER_CIRCLE_RADIUS = 130
CIRCLE_ROTATION_SPEED = 0.015  
CIRCLE_SPACING = 25
CIRCLE_WIDTH = 3
HOLE_SIZE_DEGREES = 30
HOLE_SHIFT = -15
DEFAULT_CIRCLE_NUMBERS = 30
DEFAULT_CIRCLE_NUMBERS_DISPLAY = 10
CIRCLE_FADE_OUT_FRAME = 30  
CIRCLE_FADE_IN_FRAME = 40

# Visual effects
DISSOLVE_SEGMENTS = 40
MIN_CIRCLE_WIDTH = 1
FIRE_PARTICLES = 60
FIRE_LIFETIME = 60
FIRE_SPEED = 0.5
SCORE_EFFECT_DURATION = 2

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# Timer settings
TIMER_DURATION = 61
TIMER_POSITION = (50, 50)
TIMER_RADIUS = 30
TIMER_COLOR = WHITE
TIMER_FIRE_THRESHOLD = 12
TIMER_BLINK_THRESHOLD = 8
TIMER_MAX_PARTICLES = 80

# Sound settings
MIDI_VOLUME = 0.1